<?php
/**
 * @file
 * Module to supply footer icons for ASC Sites.
 */

/**
 * @defgroup asc_footer
 * Module to supple field to add OPIC image.
 *
 * And finally, our module defines the widet in
 * opic_field_widget_info() and field_example_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function asc_footer_menu() {
  $items['admin/config/asc_footer'] = array(
    'title' => 'ASC Footer',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('asc_footer_form'),
    'access arguments' => array('administer asc_footer'),
  );
  return $items;
}

/*
 * Implements hook_permission()
 */
function asc_footer_permission() {
  return array(
    'administer asc_footer' => array(
      'title' => t('Administer ASC Footer'),
      'description' => t('Update sitewide footer.'),
    ),
  );
}

/**
 * Admin form for asc footer.
 */
function asc_footer_form($form_state) {
  $form = array();
  $fields = asc_footer_get_fields();

  foreach ($fields as $field => $value) {
    $form[$field] = array(
      '#title' => $field,
      '#description' => $field,
      '#type' => 'textfield',
      '#default_value' => $value,
    );
  }

  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  return $form;
}

function asc_footer_get_fields() {
  $prefix = 'asc_footer_';
  $fields = array(
    'address_1' => variable_get($prefix . 'Address_1'),
    'address_2' => variable_get($prefix . 'Address_2'),
    'city' => variable_get($prefix . 'City'),
    'state' => variable_get($prefix . 'State'),
    'zip' => variable_get($prefix . 'Zip'),
    'phone' => variable_get($prefix . 'Phone'),
    'fax' => variable_get($prefix . 'Fax'),
    'e_mail' => variable_get($prefix . 'E_Mail'),
    'link_1_Text' => variable_get($prefix . 'Link_1_Text'),
    'link_1_Description' => variable_get($prefix . 'Link_1_Desc'),
    'link_1_URL' => variable_get($prefix . 'Link_1_URL'),
    'link_2_Text' => variable_get($prefix . 'Link_2_Text'),
    'link_2_Description' => variable_get($prefix . 'Link_2_Desc'),
    'link_2_URL' => variable_get($prefix . 'Link_2_URL'),
    'link_3_Text' => variable_get($prefix . 'Link_3_Text'),
    'link_3_Description' => variable_get($prefix . 'Link_3_Desc'),
    'link_3_URL' => variable_get($prefix . 'Link_3_URL'),
  );
  return $fields;
}

/**
 * Form submission
*/
function asc_footer_form_submit(&$form, &$form_state){
  $fields = asc_footer_get_fields();
  foreach ($fields as $field => $value) {
   variable_set('asc_footer_' . $field, $form_state['values'][$field]);
  }
  drupal_set_message('Your settings have been saved.');
}

/*
 * Implements hook_block_info
 */

function asc_footer_block_info() {
  $blocks['asc_footer'] = array(
    'info'        => 'ASC Footer',
    'weight'      => '-10',
    'region'      => 'footer_first',
    'status'      => 'true',
    'cache'       => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/*
 * Implements hook_block_view
 */

function asc_footer_block_view($delta = '') {
  $block['subject'] = '';

  $fields = asc_footer_get_fields();

  $block['content'] = theme('asc_footer_block', $fields);

  return $block;
}


/*
 * Implements hook_theme
 */
function asc_footer_theme() {
  return array(
    'asc_footer_block' => array(
      'template' => 'asc_footer_block',
    ),
  );
}
