<?php
/**
 * @file
 * Module to supply footer icons for ASC Sites.
 */

/**
 * @defgroup asc_footer
 * Module to supple field to add OPIC image.
 *
 * And finally, our module defines the widet in
 * opic_field_widget_info() and field_example_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 */

/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function asc_footer_menu() {
  $items['admin/config/asc_footer'] = array(
    'title' => 'ASC Footer',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('asc_footer_form'),
    'access arguments' => array('administer asc_footer'),
  );
  return $items;
}

/*
 * Implements hook_permission().
 */
function asc_footer_permission() {
  return array(
    'administer asc_footer' => array(
      'title' => t('Administer ASC Footer'),
      'description' => t('Update sitewide footer.'),
    ),
  );
}

/**
 * Admin form for asc footer.
 */
function asc_footer_form($form_state) {
  $form = array();
  $fields = _asc_footer_get_fields();

  foreach ($fields as $field => $value) {
    $form[$field] = array(
      '#title' => check_plain($field),
      '#description' => check_plain($field),
      '#type' => 'textfield',
      '#default_value' => $value,
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

/**
 * Returns a list of fields in the ASC footer.
 */

function _asc_footer_get_fields() {
  $prefix = 'asc_footer_';
  $fields = array(
    'address_1' => variable_get($prefix . 'address_1'),
    'address_2' => variable_get($prefix . 'address_2'),
    'city' => variable_get($prefix . 'city'),
    'state' => variable_get($prefix . 'state'),
    'zip' => variable_get($prefix . 'zip'),
    'phone' => variable_get($prefix . 'phone'),
    'fax' => variable_get($prefix . 'fax'),
    'link_1_text' => variable_get($prefix . 'link_1_text'),
    'link_1_desc' => variable_get($prefix . 'link_1_desc'),
    'link_1_url' => variable_get($prefix . 'link_1_url'),
    'link_2_text' => variable_get($prefix . 'link_2_text'),
    'link_2_desc' => variable_get($prefix . 'link_2_desc'),
    'link_2_url' => variable_get($prefix . 'link_2_url'),
    'link_3_text' => variable_get($prefix . 'link_3_text'),
    'link_3_desc' => variable_get($prefix . 'link_3_desc'),
    'link_3_url' => variable_get($prefix . 'link_3_url'),
  );
  return $fields;
}

/**
 * Form submission.
 */
function asc_footer_form_submit(&$form, &$form_state) {
  $fields = _asc_footer_get_fields();
  foreach ($fields as $field => $value) {
    variable_set('asc_footer_' . $field, $form_state['values'][$field]);
  }
  drupal_set_message(t('Your settings have been saved.'));
}

/*
 * Implements hook_block_info().
 */

function asc_footer_block_info() {
  $blocks['asc_footer'] = array(
    'info'        => 'ASC Footer',
    'weight'      => '-10',
    'region'      => 'footer_first',
    'status'      => 'true',
    'cache'       => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/*
 * Implements hook_block_view().
 */

function asc_footer_block_view($delta = '') {
  $block['subject'] = '';

  $fields = _asc_footer_get_fields();
  $fields['e_mail'] = variable_get('site_mail');

  $block['content'] = theme('asc_footer_block', $fields);

  return $block;
}


/*
 * Implements hook_theme().
 */
function asc_footer_theme() {
  return array(
    'asc_footer_block' => array(
      'template' => 'asc_footer_block',
    ),
  );
}
